Magazine management website - An ASP.NET MVC 4 Sample/C#/Web/Areas/Admin/Controllers/DashBoardController.cs
namespace CIK.News.Web.Areas.Admin.Controllers
{
    using System.Web.Mvc;

    using CIK.News.Web.Infras;
    using CIK.News.Web.Infras.ActionResults.Admin;
    using CIK.News.Web.Infras.ViewModels.Admin.DashBoard;

    [Authorize]
    public class DashBoardController : BaseController
    {
        public ActionResult Index(int page = 1)
        {
            var viewModel = new DashBoardViewModel();
            TryUpdateModel(viewModel);

            return new DashBoardViewModelActionResult<DashBoardController>(
                x => x.Index(page),
                viewModel.TitleSearchText ?? string.Empty,
                page);
        }
    }
}

Magazine management website - An ASP.NET MVC 4 Sample/C#/Web/Areas/Admin/Controllers/ItemController.cs
namespace CIK.News.Web.Areas.Admin.Controllers
{
    using System.Web.Mvc;

    using CIK.News.Entities.NewsAgg;
    using CIK.News.Web.Infras;
    using CIK.News.Web.Infras.ActionResults.Admin;
    using CIK.News.Web.Infras.MediaItem;
    using CIK.News.Web.Infras.ViewModels.Admin.DashBoard;
    using CIK.News.Web.Infras.ViewModels.Admin.Persistences;

    [Authorize]
    public class ItemController : BaseController
    {
        #region ctors & variables
        
        private readonly IItemCreatingPersistence _itemCreatingPersistence;
        private readonly IItemEditingPersistence _itemEditingPersistence;
        private readonly IItemDeletingPersistence _itemDeletingPersistence;
        private readonly IMediaItemStorage _itemStorage;

        public ItemController(
            IItemCreatingPersistence itemCreatingPersistence, 
            IItemDeletingPersistence itemDeletingPersistence,
            IItemEditingPersistence itemEditingPersistence,
            IMediaItemStorage itemStorage)
        {
            _itemCreatingPersistence = itemCreatingPersistence;
            _itemDeletingPersistence = itemDeletingPersistence;
            _itemEditingPersistence = itemEditingPersistence;

            _itemStorage = itemStorage;
        }

        #endregion

        #region public methods

        public ActionResult Create()
        {
            return new ItemCreatingViewModelActionResult<ItemController>(x => x.Create());
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(ItemCreatingViewModel viewModel)
        {
            var item = CreateOrUpdateItem(viewModel, true);

            if (_itemCreatingPersistence.PersistenceItem(item))
                SucceedMessage("Save item successfully");
            else
                ErrorMessage("Cannot create item");

            return RedirectToAction("Index", "Dashboard");
        }

        public ActionResult Edit(int id)
        {
            return new ItemEditingViewModelActionResult<ItemController>(x => x.Edit(id), id);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ItemEditingViewModel viewModel)
        {
            var item = CreateOrUpdateItem(viewModel, false);

            if (_itemEditingPersistence.PersistenceItem(item))
                SucceedMessage("Save item successfully");
            else
                ErrorMessage("Cannot edit item");

            return RedirectToAction("Index", "Dashboard");
        }

        public ActionResult Delete(int id)
        {
            var isSucceed = _itemDeletingPersistence.PersistenceItem(id);

            if(isSucceed)
                SucceedMessage("Delete item successfully");
            else
                ErrorMessage("Cannot delete item");

            return RedirectToAction("Index", "Dashboard");
        }

        #endregion

        #region private methods

        private Item CreateOrUpdateItem(dynamic vm, bool isNew)
        {
            var smallImagePath = string.Empty;
            var mediumImagePath = string.Empty;
            var largeImagePath = string.Empty;

            if (vm.SmallImage != null)
            {
                smallImagePath = vm.SmallImage.CreateImagePathFromStream(_itemStorage);
            }

            if (vm.MediumImage != null)
            {
                mediumImagePath = vm.MediumImage.CreateImagePathFromStream(_itemStorage);
            }

            if (vm.BigImage != null)
            {
                largeImagePath = vm.BigImage.CreateImagePathFromStream(_itemStorage);
            }

            var category = CategoryFactory.CreateCategory(vm.CategoryId);
            var itemContent = ItemContentFactory.CreateItemContent(
                                    vm.Title,
                                    vm.SortDescription,
                                    vm.Content,
                                    smallImagePath,
                                    mediumImagePath,
                                    largeImagePath);

            Item item = isNew
                        ? ItemFactory.CreateItem(this.GetUserName(), category, itemContent)
                        : ItemFactory.CreateItem(vm.ItemId, this.GetUserName(), category, itemContent);

            return item;
        }

        #endregion
    }
}

Magazine management website - An ASP.NET MVC 4 Sample/C#/Web/Areas/Admin/Views/DashBoard/Index.cshtml
@model CIK.News.Web.Infras.ViewModels.Admin.DashBoard.DashBoardViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section HeaderContent{
    <script type="text/javascript">
        $(function () {
            $('#search').click(function () {
                $('form').submit();
            });
        });
    </script>
}

@{ Html.BeginForm("Index", "DashBoard", new {page = 0}); }
<!-- Content -->
<div id="content">
				
    <!-- Box -->
    <div class="box">
        <!-- Box Head -->
        <div class="box-head">
            <h2 class="left">Current News</h2>
            <div class="right">
                <label>search news</label>
                @Html.TextBoxFor(m=>m.TitleSearchText, new { Class="field small-field"})
                @*<input type="text" class="field small-field" />*@
                <input type="submit" class="button" value="search" id="search" name="search" />
            </div>
        </div>
        <!-- End Box Head -->	

        <!-- Table -->
        <div class="table">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <th width="13"><input type="checkbox" class="checkbox" /></th>
                    <th>Title</th>
                    <th>Date</th>
                    <th>Added by</th>
                    <th width="110" class="ac">Content Control</th>
                </tr>

                @foreach(var item in Model.Items)
                {
                    <tr>
                        <td><input type="checkbox" class="checkbox" /></td>
                        <td><h3><a href="#">@item.ItemContent.Title</a></h3></td>
                        <td>@item.CreatedDate.Value.ToShortDateString()</td>
                        <td><a href="#">@item.CreatedBy</a></td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", "Item", new { id = item.Id }, new { Class = "ico del" })
                            @Html.ActionLink("Edit", "Edit", "Item", new { id = item.Id }, new { Class = "ico edit" })
                            @*<a href="#" class="ico del">Delete</a>*@
                            @*<a href="#" class="ico edit">Edit</a>*@
                        </td>
                    </tr>
                }

            </table>
						
						
            <!-- Pagging -->
            @Html.Partial("_Pagination", Model.PagingData)
            <!-- End Pagging -->
						
        </div>
        <!-- Table -->
					
    </div>
    <!-- End Box -->
</div>
<!-- End Content -->
			
<!-- Sidebar -->
<div id="sidebar">
				
    <!-- Box -->
    <div class="box">
					
        <!-- Box Head -->
        <div class="box-head">
            <h2>Management</h2>
        </div>
        <!-- End Box Head-->
					
        <div class="box-content">
            @*@Html.ActionLink("Add new Article", "Create", "Item", new {Class="add-button"})*@
            <a href="/Admin/Item/Create" class="add-button"><span>Add new Article</span></a>
            <div class="cl">&nbsp;</div>
						
            <p class="select-all"><input type="checkbox" class="checkbox" /><label>select all</label></p>
            <p><a href="#">Delete Selected</a></p>
						
            <!-- Sort -->
            <div class="sort">
                <label>Sort by</label>
                <select class="field">
                    <option value="">Title</option>
                </select>
                <select class="field">
                    <option value="">Date</option>
                </select>
                <select class="field">
                    <option value="">Author</option>
                </select>
            </div>
            <!-- End Sort -->
						
        </div>
    </div>
    <!-- End Box -->
</div>
<!-- End Sidebar -->
@{Html.EndForm(); }